---
# The format of this file is documented here:
# https://github.com/quarkusio/quarkus-github-bot#triage-issues
features: [ALL]
workflows:
  rules:
    - allow:
        files:
         - "**/README.md"
workflowRunAnalysis:
  workflows: ["Quarkus CI"]
triage:
  rules:
    - labels: [feature1]
      title: "title-feature-1"
      notify: [nicolasgras]
      directories:
        - feature1
    - labels: [feature2]
      title: "feature-2"
      notify: [nicolasgras]
      directories:
        - feature2
  qe:
    notify: [nicolasgras]
